name: Deploy via FTP

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Prod

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.0.0'

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install dependencies
      run: pnpm install

    - name: Build Nuxt.js application
      run: pnpm run generate

    - name: Debug FTP secrets
      run: |
        FTP_HOST="${{ secrets.FTP_HOST }}"
        FTP_USERNAME="${{ secrets.FTP_USERNAME }}"
        FTP_PASSWORD="${{ secrets.FTP_PASSWORD }}"

        echo "FTP_HOST: $FTP_HOST"
        echo "FTP_USERNAME: $FTP_USERNAME"
        echo "FTP_PASSWORD: $FTP_PASSWORD"

    - name: Deploy to FTP server
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:        
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./dist/
        server-dir	: /